language: node_js
node_js:
    - 10
install: npm install localforage typescript tiddlywiki@$TIDDLYWIKI @types/node
script: make test

matrix:
  include:
    - env: TIDDLYWIKI=5.1.17
    - env: TIDDLYWIKI=5.1.16
    - env: TIDDLYWIKI=5.1.15

git:
    depth: 200
